# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20170609_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='remaining_quantity',
        ),
    ]
