# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_remove_item_remaining_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='max_item_quantity',
        ),
    ]
