# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_auto_20170616_1450'),
        ('sales', '0014_remove_sale_max_item_quantity'),
    ]

    operations = [
    ]
